### ISSUE TITLE
Error on apiClient.shutdownDroplet

### ISSUE THREAD

**Issue by samuelfac** [jeevatkm/digitalocean-api-java#24]
Exception in thread "main" com.myjeeva.digitalocean.exception.DigitalOceanException: 
HTTP Status Code: 403
Error Id: translation missing: en.status_code.forbidden.id
Error Message: You do not have access for the attempted action.
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.evaluateResponse(DigitalOceanClient.java:870)
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.executeHttpRequest(DigitalOceanClient.java:835)
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.doPost(DigitalOceanClient.java:806)
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.perform(DigitalOceanClient.java:763)
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.shutdownDroplet(DigitalOceanClient.java:311)

**Comment by jeevatkm** [comment]
@samuelfac - As per above exception it seems user permission issue in DigitalOcean account. I have verified the API client, it works as expected.  

Can you please describe your issue in details?

**Comment by jeevatkm** [comment]
@samuelfac can you please provide some insight for analysis?

**Comment by jeevatkm** [comment]
@samuelfac I'm closing this, please let me know if your still facing an issue. Thanks!
