### ISSUE TITLE
Android app compatiable 

### ISSUE THREAD

**Issue by haiy** [jeevatkm/digitalocean-api-java#35]
Hi, I'm trying to write an Android app with your api, but I just encounter a bug like this, would you please help me to fix it? Below is the detail of the exception,Thanks so much. 

    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.NoSuchMethodError: org.apache.http.entity.StringEntity.<init>
            at com.myjeeva.digitalocean.impl.DigitalOceanClient.createRequestData(DigitalOceanClient.java:1021)
            at com.myjeeva.digitalocean.impl.DigitalOceanClient.perform(DigitalOceanClient.java:837)
            at com.myjeeva.digitalocean.impl.DigitalOceanClient.createDroplet(DigitalOceanClient.java:278)
            at space.haiyf.app.grabword.DisplayMessageActivity$createCmd.doInBackground(DisplayMessageActivity.java:137)
            at space.haiyf.app.grabword.DisplayMessageActivity$createCmd.doInBackground(DisplayMessageActivity.java:127)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

**Comment by jeevatkm** [comment]
It seems, issue with StringEntity constructor of Android. Let me have a look and get back.

**Comment by jeevatkm** [comment]
Can you please try 2.2-SNAPSHOT version and let me know?

**Comment by haiy** [comment]
hi, @jeevatkm ,would you please published it on the [maven repo center](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.myjeeva.digitalocean%22%20AND%20a%3A%22digitalocean-api-client%22)?I can't find it here.

**Comment by jeevatkm** [comment]
It's already in snapshot repo. Refer this https://oss.sonatype.org/content/repositories/snapshots/ in build config as repository and use 2.2-SNAPSHOT as version. I will published it to maven central during a release. Please use it from Snapshot repo and share your feedback.

Link: https://oss.sonatype.org/content/repositories/snapshots/com/myjeeva/digitalocean/digitalocean-api-client/

**Comment by haiy** [comment]
ok,thanks

**Comment by haiy** [comment]
It works!Bravol!Thanks! @jeevatkm

**Comment by jeevatkm** [comment]
Thanks for your confirmation. I'm scheduling this enhancement for 2.2 release. Till that time please use 2.2-SNAPSHOT for your need.

**Comment by haiy** [comment]
Ok, thanks for your help.
